fn main() {
    // Autogeneriert pro Command `permissions/autogenerated/<command>.toml` mit
    // `allow-<kebab-command>` — die Capability muss diese IDs referenzieren.
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(
            tauri_build::AppManifest::new().commands(&[
                "read_project_manifest",
                "write_project_manifest",
                "read_project_subpath",
                "write_project_subpath",
                "save_text_file_with_dialog",
                "pick_project_folder_with_dialog",
            ]),
        ),
    )
    .expect("tauri-build failed");
}
